/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidlittleboy_fmodpractice_MainActivity */
#include <fmod.hpp>
#include <string>
#ifndef _Included_com_androidlittleboy_fmodpractice_MainActivity
#define _Included_com_androidlittleboy_fmodpractice_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_androidlittleboy_fmodpractice_MainActivity_MODE_NORMAL
#define com_androidlittleboy_fmodpractice_MainActivity_MODE_NORMAL 0
#undef com_androidlittleboy_fmodpractice_MainActivity_MODE_LUOLI
#define com_androidlittleboy_fmodpractice_MainActivity_MODE_LUOLI 1
#undef com_androidlittleboy_fmodpractice_MainActivity_MODE_DASHU
#define com_androidlittleboy_fmodpractice_MainActivity_MODE_DASHU 2
#undef com_androidlittleboy_fmodpractice_MainActivity_MODE_JINGSONG
#define com_androidlittleboy_fmodpractice_MainActivity_MODE_JINGSONG 3
#undef com_androidlittleboy_fmodpractice_MainActivity_MODE_GAOGUAI
#define com_androidlittleboy_fmodpractice_MainActivity_MODE_GAOGUAI 4
#undef com_androidlittleboy_fmodpractice_MainActivity_MODE_KONGLING
#define com_androidlittleboy_fmodpractice_MainActivity_MODE_KONGLING 5
/*
 * Class:     com_androidlittleboy_fmodpractice_MainActivity
 * Method:    voiceChangeNative
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_androidlittleboy_fmodpractice_MainActivity_voiceChangeNative
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
